<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * CLI entry point: php index.php analytics install|migrate|publish
 */
class Analytics extends CI_Controller
{
    const ROUTES_REQUIRE_LINE = "require_once __DIR__ . '/analytics_routes.php';";

    public function __construct()
    {
        parent::__construct();

        if (!is_cli()) {
            show_error('This controller can only be accessed via the command line.', 403);
        }

        $this->load->add_package_path(realpath(__DIR__ . '/../') . DIRECTORY_SEPARATOR);
        $this->load->library('analytics_lib');
    }

    public function index()
    {
        echo "Usage: php index.php analytics install|migrate|publish\n";
    }

    public function install()
    {
        echo "Analytics Installation\n";
        echo str_repeat('-', 28) . "\n\n";

        echo "\xE2\x9C\x93 Analytics package detected\n";

        $this->install_config();
        echo "\xE2\x9C\x93 Configuration loaded\n";

        $this->run_migrations();
        echo "\xE2\x9C\x93 Database tables created\n";

        $this->install_routes();
        echo "\xE2\x9C\x93 Routes registered\n";

        $this->install_stubs();
        echo "\xE2\x9C\x93 Controller stubs published\n";

        echo "\nAnalytics installed successfully.\n\n";

        $config = $this->analytics_lib->config();
        echo "Track endpoint:\n  /" . $config['track_route'] . "\n\n";
        echo "Admin dashboard:\n  /" . $config['admin_prefix'] . "\n\n";
        echo "Client script:\n  see libs/open-analytics — point its data-endpoint at the track endpoint above.\n";
    }

    public function migrate()
    {
        $this->run_migrations();
        echo "Analytics migrations are up to date.\n";
    }

    public function publish()
    {
        $this->install_stubs();
        echo "Analytics assets published.\n";
    }

    protected function install_stubs()
    {
        require_once __DIR__ . '/../core/Stub_generator.php';

        Stub_generator::generate(APPPATH . 'controllers');
    }

    protected function install_config()
    {
        $target = APPPATH . 'config/analytics.php';

        if (is_file($target)) {
            return;
        }

        copy(realpath(__DIR__ . '/../config/analytics.php'), $target);
    }

    protected function run_migrations()
    {
        $config = $this->analytics_lib->config();

        $this->load->library('migration', [
            'migration_enabled' => true,
            'migration_type' => 'sequential',
            'migration_path' => realpath(__DIR__ . '/../migrations') . DIRECTORY_SEPARATOR,
            'migration_table' => $config['tables']['migrations'],
            'migration_auto_latest' => false,
        ]);

        if (!$this->migration->latest()) {
            show_error($this->migration->error_string());
        }
    }

    /**
     * Write all Analytics routes into their own application/config/analytics_routes.php
     * file (regenerated on every install, safe to overwrite), then make
     * sure the host's application/config/routes.php requires it exactly
     * once. This keeps routes.php itself untouched apart from a single,
     * stable require line — no marker-based text surgery on a file the
     * host app may also be editing by hand.
     */
    protected function install_routes()
    {
        $config = $this->analytics_lib->config();

        file_put_contents(APPPATH . 'config/analytics_routes.php', $this->build_routes_file($config));

        $this->ensure_routes_require();
    }

    protected function ensure_routes_require()
    {
        $routes_file = APPPATH . 'config/routes.php';
        $contents = file_get_contents($routes_file);
        $line = self::ROUTES_REQUIRE_LINE;

        if (strpos($contents, $line) !== false) {
            return;
        }

        file_put_contents($routes_file, rtrim($contents) . "\n\n" . $line . "\n");
    }

    protected function build_routes_file(array $config)
    {
        $track = trim($config['track_route'], '/');
        $admin = trim($config['admin_prefix'], '/');

        $lines = [
            '<?php',
            "defined('BASEPATH') OR exit('No direct script access allowed');",
            '',
            '/*',
            ' * Auto-generated by cuongcds/ci3-analytics (`php index.php analytics install`).',
            ' * Do not edit — this file is regenerated on every install/publish. Override',
            " * track_route / admin_prefix in application/config/analytics.php instead.",
            ' */',
            '',
            "\$route['{$track}'] = 'analytics_track/track';",
            "\$route['{$admin}'] = 'analytics_admin/index';",
        ];

        return implode("\n", $lines) . "\n";
    }
}
