<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * CI3's core dispatch loop (system/core/CodeIgniter.php) only ever looks for the
 * initially-routed controller under APPPATH.'controllers/' — add_package_path()
 * only helps $this->load->model()/view()/library() calls made from *within* an
 * already-dispatched controller, not the dispatch of the very first one. So every
 * package controller needs a tiny stub in application/controllers/ that simply
 * requires the real (package) controller file, which declares the class CI3 is
 * looking for. `analytics install` generates these; this class holds the shared
 * logic so both `install` and the self-healing check in bootstrap.php can reuse it.
 */
class Stub_generator
{
    public static function stubs(): array
    {
        $adapterRoot = realpath(__DIR__ . '/../');

        return [
            // NOTE: the CLI controller stays a top-level file named exactly
            // Analytics.php (CI3's CLI routing convention requires it). The public
            // track endpoint and the admin dashboard therefore live under
            // different names/directories (Analytics_track.php, analytics_admin/)
            // so a bare `analytics` URI segment always resolves to the CLI
            // controller without colliding with either of them.
            'Analytics.php' => $adapterRoot . '/controllers/Analytics.php',
            'Analytics_track.php' => $adapterRoot . '/controllers/Analytics_track.php',
            'analytics_admin/Index.php' => $adapterRoot . '/controllers/analytics_admin/Index.php',
        ];
    }

    /**
     * Write (or rewrite) every stub. Idempotent — safe to call on every install/publish.
     */
    public static function generate(string $applicationControllersPath): void
    {
        foreach (self::stubs() as $relativePath => $realFile) {
            $target = rtrim($applicationControllersPath, '/\\') . DIRECTORY_SEPARATOR . str_replace('/', DIRECTORY_SEPARATOR, $relativePath);
            $dir = dirname($target);

            if (!is_dir($dir)) {
                mkdir($dir, 0755, true);
            }

            file_put_contents($target, self::stub_contents_for($realFile, $dir));
        }
    }

    /**
     * @param string $realFile Absolute path to the real package controller.
     * @param string|null $fromDir Directory the generated stub will live in — when given,
     *   the require path is written relative to it (via __DIR__) instead of as a baked-in
     *   absolute path, so the stub keeps working if the codebase is later moved/copied to
     *   a different absolute path (a different machine, container, deploy directory, etc.).
     */
    public static function stub_contents_for(string $realFile, ?string $fromDir = null): string
    {
        if ($fromDir !== null) {
            $relative = self::relative_path($fromDir, $realFile);
            $requireExpr = '__DIR__ . ' . var_export('/' . $relative, true);
        } else {
            $requireExpr = var_export($realFile, true);
        }

        return <<<PHP
<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
 * Auto-generated by cuongcds/ci3-analytics (`php index.php analytics install`). Do
 * not edit — this file only exists because CI3 requires the initially-routed
 * controller to live under application/controllers/. The real implementation
 * lives in the package itself and is required here unchanged.
 */
require_once {$requireExpr};

PHP;
    }

    protected static function relative_path(string $fromDir, string $toFile): string
    {
        $from = explode(DIRECTORY_SEPARATOR, rtrim(str_replace('/', DIRECTORY_SEPARATOR, $fromDir), DIRECTORY_SEPARATOR));
        $to = explode(DIRECTORY_SEPARATOR, str_replace('/', DIRECTORY_SEPARATOR, $toFile));

        while (count($from) && count($to) && $from[0] === $to[0]) {
            array_shift($from);
            array_shift($to);
        }

        $relative = str_repeat('..' . DIRECTORY_SEPARATOR, count($from)) . implode(DIRECTORY_SEPARATOR, $to);

        return str_replace(DIRECTORY_SEPARATOR, '/', $relative);
    }
}
